app:
  image: ibmcom/swift-ubuntu
  ports:
    - "8090:8090"
  volumes:
    - .:/root/SwiftForum
  command: bash -c "cd /root/SwiftForum && swift build --clean && swift build && ./.build/debug/SwiftForum"
